set(CMAKE_AR				llvm-ar${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_ASM_COMPILER		clang${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_C_COMPILER		clang${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_CXX_COMPILER		clang++${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_LINKER			lld${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_OBJCOPY			llvm-objcopy${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_RANLIB			llvm-ranlib${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_SIZE				llvm-size${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_STRIP				llvm-strip${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_GCOV				llvm-cov${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")

set(CMAKE_POSITION_INDEPENDENT_CODE	ON)
set(CMAKE_SHARED_LINKER_FLAGS		"${CMAKE_SHARED_LINKER_FLAGS} -s")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(SOURCE_TARGET	linux)
set(TARGET_CPU		"x64")

set(PROJECT_LIBRARIES_OS		-static-libgcc -static-libstdc++ pulse udev)

set(WEBRTC_COMPILE_DEFINITIONS	PUBLIC WEBRTC_LINUX WEBRTC_POSIX)
set(WEBRTC_LIBRARIES_OS			X11)