set(CMAKE_AR				gcc-ar${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_ASM_COMPILER		gcc${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_C_COMPILER		gcc${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_CXX_COMPILER		g++${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_LINKER			ld${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_OBJCOPY			objcopy${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_RANLIB			ranlib${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_SIZE				size${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_STRIP				strip${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_GCOV				gcov${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")

set(CMAKE_POSITION_INDEPENDENT_CODE	ON)
set(CMAKE_SHARED_LINKER_FLAGS		"${CMAKE_SHARED_LINKER_FLAGS} -s")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(SOURCE_TARGET	linux)
set(TARGET_CPU		"x64")

set(PROJECT_LIBRARIES_OS		-static-libgcc -static-libstdc++ pulse udev)

set(WEBRTC_COMPILE_DEFINITIONS	PUBLIC WEBRTC_LINUX WEBRTC_POSIX)
set(WEBRTC_LIBRARIES_OS			X11)